### ISSUE TITLE
unknown encoding: 8bit

### ISSUE THREAD

**Issue by lechuhuuha** [OfimaticSRL/parsemail#1]
hi i currently use your repo to get subject from email header and encountered this error
unknown encoding: 8bit

Here is the full email content [notepad](https://anotepad.com/notes/7wd7a6ba)

Here is the subject that cause error
```
Subject: Safebook =?utf-8?Q?G=E1=BB=ADi?= link tham
 =?utf-8?Q?d=E1=BB=B1_H=E1=BB=99i_th=E1=BA=A3o_?=
 =?utf-8?Q?thu=E1=BA=BF?= online =?utf-8?Q?ng=C3=A0y?= 18/03
```
And when using your repo i still get lost space in subject header

The correct header : 
`Safebook Gửi link tham dự Hội thảo thuế online ngày 18/03`

After using your repo to get email subject i got this header
`SafebookGửi link thamdự Hội thảo thuế onlinengày 18/03`

Its lost space and make the subject look very unprofessional

Can you check the error? Thanks

**Comment by xhit** [comment]
Fixed.

Please use the master branch.

**Comment by lechuhuuha** [comment]
hi thanks for 8bit fix and i had use the lastest version
 but when i use the repo to get the header i still encounter the error

The correct header :
`Safebook Gửi link tham dự Hội thảo thuế online ngày 18/03`

After using your repo to get email subject i got this header
`SafebookGửi link thamdự Hội thảo thuế onlinengày 18/03`

Its lost space between character

Can you check the error? Thanks
